### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by Old-Geek** [danbee/persephone#19]
Hello,

Just for information, the CPU load is 70%, it's huge.

Persephone v0.10.3a, MacOS Mojave.

**Comment by danbee** [comment]
Hi @Old-Geek, can you give me some more details of your setup? The CPU load can spike when it's loading album art, as it does a lot of image resizing and caching at this point.

**Comment by Old-Geek** [comment]
Indeed, it is the loading of the covers which poses problem, sorry.
It's very very slow

[https://i.imgur.com/63PbIFT.png](url)

**Comment by danbee** [comment]
Are you using especially large cover images? I have managed to improve performance a little in the latest build, not necessarily in terms of CPU usage (encoding JPEG's takes the cycles it takes!) but UI responsiveness is better while it's caching.

**Comment by Old-Geek** [comment]
I have everything but some images can do 3600x3600px (scan) up to 10MB

**Comment by danbee** [comment]
3600x3600 is pretty big! The app is resizing that down to 360x360 pixels for the album list. It should only be doing this once though as it is then caching the art, so once the app has loaded all your art it shouldn't have to do that work again.

**Comment by danbee** [comment]
@Old-Geek I just cut a new release. Would love to know if this improves performance for you: https://github.com/danbee/persephone/releases/tag/v0.11.0-alpha

**Comment by Old-Geek** [comment]
Thank you for your attention :)

But do not waste your time for me, I also made my own MPD client. I was looking for ideas to improve my application and it was by looking at what was happening that I noticed this problem.

I'll report another problem, all the covers do not load correctly. 48 were not loaded on 411 :o)

https://i.imgur.com/0l6mJvk.jpg

**Comment by danbee** [comment]
Your client looks pretty neat! It's about time there were more clients for macOS. I hope you don't mind me taking inspiration from your app for improvements to mine.

I have noticed some issues with getting particular cover images for the album view, but I haven't tracked them all down. My app finds the art by searching for the first track of the album, and some of my albums either have no track numbers, or the first track artist is not the same as the album artist, and thus the search fails.

I also think that sometimes if the track numbers have leading zeros, but haven't fully confirmed that theory. Would you mind taking a look at the tags on any albums that are not showing artwork for anomalies like that?

<img width="1288" alt="Screenshot 2019-04-02 at 14 48 01" src="https://user-images.githubusercontent.com/165531/55428235-aaa50280-5556-11e9-81c3-bef528533d14.png">

**Comment by Old-Geek** [comment]
Inhale everything you like, it's on github for that :)

Inhale everything you like, it's on github for that :)

I have no problem with tag, I'm pretty careful on that side.(I checked again to be sure)

Personally I take the path of the album to get the file cover.jpg but unlike you I use the apache server built into MacOs to get them, no direct access because I also use MPD with my smartphone. It's easier for me. To resize the images I also do it by a PHP script that I declare or not in the preferences, it's less work on smartphones or machine weak.

![2](https://user-images.githubusercontent.com/45225489/55431173-24a5ad80-5590-11e9-854b-506dc74d3e44.jpg)


![1](https://user-images.githubusercontent.com/45225489/55431018-ba8d0880-558f-11e9-9a7a-cb63c0043d0d.jpg)
