### ISSUE TITLE
Albums are shown once for every year a track is tagged

### ISSUE THREAD

**Issue by clauseggers** [danbee/persephone#43]
The albums are shown once for every unique year a track in said album is tagged. [Screenshot](https://i.imgur.com/kWTzE6x.png).

**Comment by danbee** [comment]
Hmmm... this is interesting, but not totally unexpected behaviour based on how I'm fetching albums. I'm curious though, why are different tracks in a single album tagged with different years?

This looks like a simple fix though, so expect it to make its way into 0.16.0-alpha.

**Comment by danbee** [comment]
Actually, I think I can get this fix out in a 0.15.2 release tomorrow.

**Comment by clauseggers** [comment]
In compilations tracks are most often from different years (at least that is how I tag them. Tagging them with the year of release is not useful information, and if anything misleading and confusing.)

**Comment by danbee** [comment]
So the interesting thing about that is that I'm displaying a release year in the album detail view. This will currently come from the first track of the album. Should I be dealing with this a different way? Perhaps I could hide the year unless all the tracks are tagged with the same year.

**Comment by danbee** [comment]
@clauseggers Here is a pre-alpha with the fix made for this. Please try it and let me know how it works for you.

Note: The version in the about box has not been updated but the build number should be 323.

https://f001.backblazeb2.com/file/persephone/Persephone-0.15.2-prealpha.zip

**Comment by clauseggers** [comment]
Music.app shows the last year of all the tracks in the album view. I would either show no year or the span, eg. 1987–1998 in these cases.

**Comment by danbee** [comment]
The span is a good idea. I'll add that to the backlog.

**Comment by danbee** [comment]
@clauseggers Did this build work ok for you?

**Comment by clauseggers** [comment]
I’m using the 0.15.2 from the homepage, and so far so good. Thanks!
