### ISSUE TITLE
Feature request: Volume controls

### ISSUE THREAD

**Issue by odkr** [danbee/persephone#44]
Thanks *a lot* for Persephone. It’s the first MPD client I’ve seen that has a decent UI. I’m not sure whether you’re already accepting feature requests, but you know, volume controls would be nice.

**Comment by danbee** [comment]
@odkr thanks for your kind words, and for reminding me that not everyone uses mpd on their local machine with it's own volume control!

I have output management on my big list of features to add, but I will make adding a volume control more of a priority. I can't promise anything in terms of timing though I'm afraid but my guess would be that it will make it's way into the 0.17 or 0.18 release.

**Comment by odkr** [comment]
Thanks a lot!

**Comment by danbee** [comment]
@odkr If you're brave, there's a [prealpha release here](https://f001.backblazeb2.com/file/persephone/Persephone-0.16.0-prealpha.zip) with a volume control. It seems it was much easier to add than I first thought! So this will make it into the 0.16.0 release, which will likely be out for real some time next week.

**Comment by odkr** [comment]
Thanks! I've just downloaded it and so far everything runs smoothly. <Cmd>-<A> doesn’t work in the search box though.
