### ISSUE TITLE
Feature request: Keyboard shortcuts

### ISSUE THREAD

**Issue by clauseggers** [danbee/persephone#50]
Feature request: Keyboard shortcuts for the most basic features like Play/Pause (I suggest using the space-bar), and left/right arrow keys for previous/next track.

**Comment by danbee** [comment]
Space for play/pause should already work, although I think there's an issue with the responder chain somewhere that means that sometimes it doesn't.

**Comment by clauseggers** [comment]
I don’t remember that play/pause on space has ever worked for me, but the database update on alt+cmd+u has.

**Comment by danbee** [comment]
Thanks, I'll look into this soon. I haven't noticed because I mostly control Persephone with the media keys.

**Comment by danbee** [comment]
Fixed in [0.17.0-alpha](https://github.com/danbee/persephone/releases/tag/0.17.0-alpha). I added previous and next as ⌘← and ⌘→ to lessen the chance of hitting them accidentally (I consider them "destructive")
