### ISSUE TITLE
Feature request: playlists

### ISSUE THREAD

**Issue by treasuretron** [danbee/persephone#57]
Thank you so much for making Persephone! This is making my migration from itunes to mpd much easier :)

But, any plans to support playlists?

thanks!!

**Comment by danbee** [comment]
Yep, it's on the list! It'll likely be the next thing I work on.

**Comment by treasuretron** [comment]
woohoo!! Awesome

**Comment by danbee** [comment]
This is currently being worked on, but figuring out the UI has been tricky.

**Comment by danbee** [comment]
Closing this as it's in progress
