### ISSUE TITLE
Allow album grouping by Album Artist field instead of Artist (& sort variants)

### ISSUE THREAD

**Issue by cortices** [danbee/persephone#63]
In a great many albums especially Classical music and compilations, individual tracks have different artist fields. This may include identifying particular soloists, or completely different performers/ensembles. As such, the Album Artist field functions as a field to summarise and group the tracks by their real album (and still provides differentiation for genuinely different albums with identical names, for example "Solo" or "E.P."

I'm not certain about how MPD backend provides album lists but I understand it's configurable whether to arrange by Artist, Album Artist, or the 'Sort' versions of those tags (falling back where appropriate). Could Persephone expose this option?

**Comment by danbee** [comment]
@cortices It's certainly possible. Currently Persephone groups tracks by AlbumArtist which I think works well the vast majority of the time.

**Comment by benjaminwil** [comment]
I was having a similar issue. It turns out that my mpd configuration file (the default one, I think) does not include `albumartist` in the `metadata_to_use` settings array.

Once I added this and updated my library, all of my "duplicate" albums disappeared and were suddenly sorted by `AlbumArtist`. 👍

**Comment by danbee** [comment]
@benjaminwil I wasn't aware that option even exists! Thanks.

**Comment by cortices** [comment]
@benjaminwil’s solution solved the issue. Apparently the true problem is that currently the default mpd config file ignores Album Artist fields entirely, contrary to the expectations of some users.
