### ISSUE TITLE
Bug: Persephone v0.17.2alpha - Hitting backspace when nothing is selected causes a crash

### ISSUE THREAD

**Issue by odkr** [danbee/persephone#65]
The title says it all really ;-). I’m still on macOS v10.14.6.

**Comment by danbee** [comment]
@odkr Thanks for the report! I'll look into this

**Comment by danbee** [comment]
Fixed in [0.17.3-alpha](https://github.com/danbee/persephone/releases/tag/0.17.3-alpha).
