### ISSUE TITLE
Bug: Graphics slowdown with large library

### ISSUE THREAD

**Issue by nopeinomicon** [danbee/persephone#69]
I have a library of over 1tb in size, and I am trying to use Persephone to manage it and play it (as nothing that isn't MPD based stacks up on Mac in my eyes right now), however with my full library loaded into the app the visual effects of the app and window redraw become sluggish and choppy.

**Comment by danbee** [comment]
@nopeinomicon Can you take a video of what you're seeing? I know Persephone can be a little choppy while loading/resizing all the album art but it's in the realm of acceptable for me (and my library is similarly large).

Are your album cover files especially large?

**Comment by nopeinomicon** [comment]
It may have been my MacOS install, unsure at this time. I switched back to Linux again so I can no longer test this, so I'll close the issue. Thanks for working on this program though!
