### ISSUE TITLE
404 error on download link on persephone.fm

### ISSUE THREAD

**Issue by ImaCrea** [danbee/persephone#91]
title is pretty clear

thank you for this great project!

**Comment by Dobbie03** [comment]
404 still exists.  How do we download this?

**Comment by co-dan** [comment]
I think you can download it from GitHub: https://github.com/danbee/persephone/releases/tag/0.18.1-alpha

**Comment by danbee** [comment]
OMG, I can't believe this one has been broken so long. Fixed now.
